version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Building the Go code...
      - cd $CODEBUILD_SRC_DIR/.
      - go build main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - main
